version: '3'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "discovery.type=single-node"

  redis:
    container_name: redis-container
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  api:
    container_name: api-container
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./.env

  nginx:
    container_name: nginx-container
    image: nginx:1.19.2
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/configs:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db_volume:
