version: '3'

services:
  movies-elasticsearch:
    container_name: movies-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "discovery.type=single-node"
    networks:
      - movies-network

  movies-redis:
    container_name: movies-redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - movies-network

  movies-backend:
    container_name: movies-backend
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - movies-elasticsearch
      - movies-redis
    env_file:
      - ./.env
    networks:
      - movies-network

  movies-nginx:
    container_name: movies-nginx
    image: nginx:1.19.2
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/configs:/etc/nginx/conf.d
    depends_on:
      - movies-backend
    ports:
      - "8002:8002"
    networks:
      - movies-network

networks:
  movies-network:
    external:
      name: movies-network

volumes:
  db_volume:
