version: '3'

services:
  movies-elasticsearch-test:
    container_name: movies-elasticsearch-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "discovery.type=single-node"

  movies-redis-test:
    container_name: movies-redis-test
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  movies-api-test:
    container_name: movies-api-test
    image: movies-api-test
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - movies-elasticsearch-test
      - movies-redis-test
    env_file:
      - ./.env.test

  tests:
    container_name: tests
    image: movies-api-test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: pytest
    depends_on:
      - movies-api-test
    env_file:
      - ./.env.test
